export const POST_RECEIVED = 'POST_RECEIVED'
export const POST_COMMENT_ADDED = 'POST_COMMENT_ADDED'
export const POST_COMMENT_EDITED = 'POST_COMMENT_EDITED'
export const POST_COMMENT_DELETED = 'POST_COMMENT_DELETED'